server:
  port: 9003

logging:
  file:
    name: log/logdemo.log
  pattern:
    #???????????
    console: "%d{HH:mm:ss.SSS} %level[%thread]%logger{15} %msg%n"
    #????????????
    file: "%d{HH:mm:ss.SSS} %level[%thread]%logger{15} %msg%n"
  #?????? ????, loggin.level.root?????
  level:
    com.shang.logdemo: trace