server:
  port: 9012

minio:
  endpoint: http://127.0.0.1:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: file

spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

