server:
  port: 9002

spring:
  application:
    name: spring-security-demo
  profiles:
    active: dev-home

mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:mapper/*.xml, classpath:mybatis/mapping/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.shang.**
  global-config:
    db-config:
      #主键类型  AUTO(0):"数据库ID自增", INPUT(2):"用户输入ID",ASSIGN_ID(3):"全局唯一ID (数字类型唯一ID)", ASSIGN_UUID(4):"全局唯一ID UUID";
      id-type: auto
      insert-strategy: not_null
      update-strategy: not_null
      #驼峰下划线转换
      tableUnderline: true
      #逻辑删除配置（下面3个配置）
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false