server:
  port: 8100

spring:
  cloud:
    gateway:
      routes:
        - id: rout_test1
          uri: https://www.baidu.com
          predicates:
            - Path=/visitor/**
          filters:
            # StripPrefix=1就代表截取路径的个数
            - StripPrefix=1